- name: Salade de riz composée  thon oeufs poivron tomates 
  composants:
  - name: riz
    size: 240g
  - name: thon
    size: 280g
  - name: oeuf dur
    size: 3
  - name: poivron
    size: 1
  - name: tomate
    size: 2
  - name: huile olive
    size: 1 CS
  - name: moutarde
    size: 1 a 2 CS
  - name: graines
  recipe:
  - 0 , Cuire le riz et le mettre à refroidir
  - 1 , Cuire les oeufs, 10 min après ébullition
  - 2 , Couper Oeuf tomates et poivron en dés
  - 2 , Preparer vinaigrette avec huile olive, vinaigre balsamique moutarde, sel et poivre et un peu d'eau pour détendre la vinaigrette
  - 3 , Tout mélanger dans un saladier 
  - 4 , ajouter des cornichons 
  - 5 , Laisser refroidir 1 h
- name: Salade de pomme de terre thon
  composants:
  - name: pomme de terre
    size: 800g
  - name: thon
    size: 280g
  - name: haricot rouge
    size: 250g
  - name: cacahouette
    size: 3 poignees
  - name: huile de colza
    size: 3 CS
  - name: vinaigre balsamique
    size: 3 CS
  - name: graine de courge
    size:
  - name: graine de sesame
    size:
  - name: graine de tournesol
    size:
  recipe:
  - Faire cuire les pommes de terre (cookeo 30 min) , laisser refroidir
  - Couper les patates en morceaux
  - Melanger le thon et le reste des ingrédients
  - Ajouter 3 CS de vinaigne balsamique et 3 CS de huile de colza
- name: 6 crepes vegan
  composants:
  - name: farine
    size: 250g
  - name: lait riz coco
    size: 200cl
  - name: huile olive
    size: 1 CS
- name: Patate douce, orange et noix de pecans
  composants:
  - name: patates douces
    size: 1 kg
  - name: noix de pecan
    size: 80 g
  - name: beurre
    size: 70 g
  - name: casonade
    size: 3 CS
  - name: jus d'orange
    size: 20 cl
  recipe:
  - 0/ Eplucher et couper les patates douces en cube
  - 1/ Passer le cookeo en mode dorer
  - 2/ Mettre les noix de pecans à part.
  - 3/ Faire revenir beurre + patate douces + cassonade pendant 2 min
  - 4/ Ajouter jus d'orange + sel + poivre 
  - 5/ Lancer le mode sous pression 11 min
  - 6/ Faire dorer les noix de pecans 2 min à la poele 
  - 7/ Ajouter les noix de pecans à la fin.
- name: Pizza vege
  composants:
  - name: levure boulangere
    size: 1 sachet
  - name: farine
    size: 350 g
  - name: sauce tomate concentré
    size: 70 g
  - name: tomate ou tomate cerise
    size: 1 ou 5
  - name: poivron
    size: 1/2
  - name: oignon
    size: 1/2
  - name: fromage rapé
    size: 200 g
  - name: herbe de provence
    size: juste saupoudrer
  - name: huile olive
    size: 2 CS
  - name: sel
    size: 2 pincé
  - name: sucre
    size: 2 pincée
  recipe:
  - 0, Verser la farine dans un saladier
  - 1, Ajouter une pincée de sel et de sucre et melanger
  - 2, Ajouter la levure boulangere et mélanger 
  - 3, Ajouter les 2 CS d'huile d'olive puis mélanger
  - 4, Ajouter 250 ml (max) d'eau tiede par lot de 50 ml et mélanger à chaque fois jusqu'a obtenir une pate sans farine seche et sans etre liquide 
  - 5, Laisser reposer dans le four pendant 10 min si levure boulangere instantanée
  - 6, Couper les tomates, poivrons et oignons en lamelle
  - 7, Prechauffer le four à 180°C
  - 7, Nettoyer la table puis mettre de la farine dessus 
  - 8, Petrir la pate en mettant regulierement de la farine sur ses mains pour que ca ne colle pas
  - 9, Faire cuire la pate 10 min à 180°C
  - 10, Etaler généreusement le concentré de tomate sur toute la pate
  - 11, Ajouter les légumes et le fromage
  - 12, Faire cuire au four 10-20 min à 200°C sur du papier cuisson, le temps que le fromage fonde.
- name: porridge
  composants:
  - name: lait coco
    size: 120 ml
  - name: sirop erable
    size: 1 cs
  - name: flocon avoine
    size: 30g
  - name: fruits frais ou sec (pomme banane poire)
    size: none
  - name: graine de chia
    size: 1 cs
  - name: copeau de noix de coco/raisin
    size: none
  recipe:
  - 0, Verser le lait de coco dans un bol
  - 1, Verser le sirop d'erable puis melanger puis les graines de chia et mélanger et eventuellement le chocolat en poudre amer
  - 2, Verser les flocons d'avoine et mélanger doucement.
  - 4, Laisser une nuit au frigo
  - 5, Ajouter des fruits frais ou sec le matin
